feat: enable FirstSunset on mainnet
bnb-chain/node pull request #1016
Opened 2024-04-01 03:37 UTC by j75689

### Description

This PR add the FirstSunset height to mainnet config.

### Rationale

The target fork time is `2024/4/15/ 06:00:00 UTC+0`(1713160800)
Current Block time: `2024/4/1 03:25:38 UTC+0`(1711941938)
Avg Block Time: 19/11 ~=1.73

Target Fork Block Height: (1713160800 - 1711941938)/1.73 + 372822440 ~= `373526985`

### Example

n/a

### Changes

Notable changes: 
n/a

### Preflight checks

- [x] build passed (`make build`)
- [x] tests passed (`make test`)
- [x] integration tests passed (`make integration_test`)
- [x] manual transaction test passed (cli invoke)

### Already reviewed by

n/a

### Related issues

n/a

2024-04-01 04:04 UTC, zjubfd approved these changes

2024-04-01 04:24 UTC, zjubfd requested changes
please change the version and changelogs

2024-04-01 04:50 UTC, forcodedancing approved these changes

2024-04-01 05:09 UTC, zjubfd approved these changes

2024-04-01 05:09 UTC, merged

2024-04-26 22:18 UTC, Bassambmbmbm commented
> يرجى تغيير الإصدار وسجلات التغيير

مرحبا .. كيف يمكنني هذا ...؟ BNB CHAIN

Staking

Staking

Validators

36/55

Bonded Tokens

22,692,254.5076 BNB

Guide

• BNB Beacon Chain Staking Guides

• Staking With Ledger Hardware

2024-04-26 22:58 UTC, Bassambmbmbm commented
كيفية سحب هذا لرصيد bnb ....

2026-07-05 14:32 UTC, Tarzan1313 commented
Skip to content
bnb-chain
node
Repository navigation
Code
Issues
Pull requests
Agents
Actions
Projects
Security and quality
Insights
Releases v0.10.19
v0.10.19
@github-actions github-actions released this Mar 4, 2024
 v0.10.19
 911507e 
Changelog
This is the release to enable the first sunset upgrade of BNB Beacon Chain testnet.

The BNB Beacon Chain testnet is expected to have a scheduled hard fork upgrade at block height 50,121,232. Based on the current block generation speed, the hard fork is forecasted to occur on 4th March 2024. at 6:00 (UTC). The full node runners on testnet must switch their software version to v0.10.19 by 4th March.

Background of BC Sunset
With the quick evolution of BSC, the Beacon Chain has become a burden. The cross-chain bridge that connects the two chains slows down the development iteration and always exposes BNB to a certain level of security vulnerabilities. BEP333 proposes to migrate the functionality of Beacon Chain to BSC, allowing Beacon Chain to retire.

The Beacon Chain Sunset is divided into multiple stages: first sunset upgrade, second sunset upgrade and final sunset upgrade. The first sunset upgrade is the first milestone of BEP333.

FEATURES
#977 [BEP] feat: implement BEP-333(BNB Chain Fusion)
BUGFIX
#1014 [fix] fix: publish completed UnbondingDelegation events to kafka in EndBlock
#1015 [fix] fix: publish ChainUndelegate event and ledger sig issue
Assets
Assets	Sha256 Checksum
mainnet_config.zip	ae6f1444547d678865d2275a688fd5113a4a8b48fa16af2304ec45d067539c52
testnet_config.zip	a670936f33bab2059790b9195946f919d95e325c49d0ea84e171825315077e54
linux_binary.zip	f06d584a9604c77dc7db90ba7b2fa7b198969af951192fc6b875bf33b837b661
macos_binary.zip	0e7f30618537ae52688c401818b534fadfb86a86cd94a3180e3658857009d4d2
windows_binary.zip	77734320b3cd88e89356ead9ecb5bfc9f1ff297ee781e586e688a17292847d67
Assets
7
linux_binary.zip
87.9 MB
Mar 4, 2024
macos_binary.zip
92.6 MB
Mar 4, 2024
mainnet_config.zip
12.9 KB
Mar 4, 2024
testnet_config.zip
9.66 KB
Mar 4, 2024
windows_binary.zip
82.3 MB
Mar 4, 2024
Source code
(zip)
Mar 4, 2024
Source code
(tar.gz)
Mar 4, 2024
Footer
© 2026 GitHub, Inc.
Footer navigation
Terms
Privacy
Security
Status
Community
Docs
Contact
Manage cookies
Do not share my personal information