bep173: enable text proposal on BNB Smart Chain
bnb-chain/node pull request #893
Opened 2022-11-21 07:06 UTC by Pythonberg1997

## Motivation

In some scenarios, the community may need a proposal that does not directly cause any changes, like agreeing to a certain strategy, plan, commitment or other statement.

## Specification

Right now, there are many system parameters that control the behavior of the BSC, e.g. slash amount, cross-chain transfer fees. All these parameters can be determined by the BSC Validator Set together through a proposal-vote process based on staking. The process executes on the BC and the new parameter values will be picked up by either the management module on the BC or corresponding system contracts via the cross-chain communication protocol. The proposals can be classified into two groups: 

1. Param Change Proposal if the parameter takes effect on the Beacon Chain; 

2. Cross Param Change Proposal if the parameter takes effect on the BNB Smart Chain.

This proposal introduces a new kind of proposal to agree on a certain strategy, plan, commitment, future upgrade, or other statements. **Text proposals** are exclusively a signaling mechanism and focal point for future coordination - they do not directly cause any changes on-chain.

## Commands:

Submit Text Proposal

./tbnbcli gov submit-proposal --type text …[flags]

Query Proposal

./tbnbcli gov query-proposal --proposal-id {id} ...[flags]

Voting 

./tbnbcli gov vote --option yes --proposal-id {id} ...[flags]

2022-11-21 07:28 UTC, forcodedancing submitted a review, later dismissed

2022-11-21 07:38 UTC, guagualvcha commented on asset/testnet/app.toml
> +BEP173Height = 9223372036854775807
Please add the mainnet hardfork height.

2022-11-21 07:39 UTC, guagualvcha commented on plugins/bridge/pub.go
> +			event := pubsub.CrossTransferEvent{
Please delete the debug code.

2022-11-21 07:39 UTC, guagualvcha requested changes
Need modification

2022-12-01 03:32 UTC, guagualvcha approved these changes

2022-12-01 03:35 UTC, forcodedancing commented on asset/testnet/app.toml
> +BEP173Height = 9223372036854775807
Should we change this height?

2022-12-01 03:39 UTC, forcodedancing approved these changes

2022-12-01 03:42 UTC, owen-reorg approved these changes

2022-12-01 03:45 UTC, merged