fix: clear up side vote addrs
bnb-chain/node pull request #964
Opened 2023-07-05 09:00 UTC by NathanBSC

### Description

clear up all vote addrs when the height of new hardfork reached

### Rationale

a part of solving rogue key attack
refer to https://github.com/bnb-chain/bnc-cosmos-sdk/pull/353

### Example

### Changes
1. clear up all existed vote address when the height of hardfork reached
2. upgrade go version to 1.19 and upgrade go lint to 1.53.3
3. modify Dockerfile, add more package needed when compile and run

PS: change github.com/tendermint/crypto to new created github.com/bnb-chain/tendermint-crypto
github.com/bnb-chain/tendermint-crypto is based on golang.org/x/crypto@v0.5.0 which others mod needed

2023-07-05 09:33 UTC, Pythonberg1997 commented
Please check the CI issues

2023-07-05 12:06 UTC, guagualvcha approved these changes

2023-07-05 12:07 UTC, guagualvcha requested changes
CI issue

2023-07-06 12:30 UTC, guagualvcha approved these changes

2023-07-06 13:26 UTC, merged